apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-spring
  namespace: mon-namespace-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-spring
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
      - name: springboot
        image: ghsourour/epi:v2
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/course_management"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "test"
        ports:
        - containerPort: 9090
        securityContext:
         allowPrivilegeEscalation: false
         runAsNonRoot: true 
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      
---
apiVersion: v1
kind: Service
metadata:
  name: app-spring-service
  namespace: mon-namespace-test
spec:
  type: NodePort
  selector:
    app: app-spring
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30080

