name: Deploy srpingapp
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4   
      - name: Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: verfier dockerfile avec hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
         dockerfile: Dockerfile     
         format: table 

      - name: Construire l'image Docker localement  
        run: |
           if docker build -t eppepi . ; then
            echo "Image Docker eppepi construite avec succès."
           else
            echo "Échec de la construction de l'image Docker ."
           fi || true  

      - name: Run dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: eppepi
          format: table     

      - name: Taguer et pousser l'image sur Docker Hub
        run: |
         docker tag eppepi ${{ secrets.DOCKER_USERNAME }}/eppepi:v1 || true
         docker push ${{ secrets.DOCKER_USERNAME }}/eppepi:v1

      - name: Run dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: eppepi:v1
          format: table 
      
      - name: Scanner l'image avec Trivy 
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: eppepi
          severity: LOW,MEDIUM,CRITICAL
          scanners: vuln
          ignore-unfixed: true   