name: Deploy srpingapp
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4   

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: auto 
          #format: table
          args: --json --output semgrep-results.json
      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json
      

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: View Dockerfile content for debugging
        run: cat Dockerfile # Ceci affichera le contenu du fichier dans les logs
      - name: verfier dockerfile avec hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
         dockerfile: Dockerfile     
    
      - name: Construire l'image Docker localement  
        run: |
           if docker build -t eppepi . ; then
            echo "Image Docker eppepi construite avec succès."
           else
            echo "Échec de la construction de l'image Docker ."
           fi || true  

   

      - name: Taguer et pousser l'image sur Docker Hub
        run: |
         docker tag eppepi ${{ secrets.DOCKER_USERNAME }}/eppepi:v1 || true
         docker push ${{ secrets.DOCKER_USERNAME }}/eppepi:v1

      - name: Run dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/eppepi:v1
          format: table 
          exit-level: info
          args: --accept-key
          exit-code: 0 


      - name: Scanner l'image avec Trivy 
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: eppepi
          severity: LOW,MEDIUM,CRITICAL
          scanners: vuln
          ignore-unfixed: true   